AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Sends an email with voucher purchase confirmation to provided email. Attaches a PDF with the voucher.
Resources:
  sendemailvoucherpurchase:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: 'Sends an email with voucher purchase confirmation to provided email. Attaches a PDF with the voucher.'
      MemorySize: 128
      Timeout: 6
      Role: 'ARN_OF_YOUR_IAM_ROLE'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /send_email_voucher_purchase
            Method: ANY
      Environment:
        Variables:
          MAILGUN_API_KEY: MAILGUN_API_KEY
          MAILGUN_API_URL: MAILGUN_API_URL
          MAILGUN_POSTMASTER_MAIL: MAILGUN_POSTMASTER_MAIL
          MAILGUN_USER_MAIL: MAILGUN_USER_MAIL
          S3_BUCKET_NAME: S3_BUCKET_NAME
          S3_FILE_KEY: S3_FILE_KEY

